### ISSUE TITLE
Turning off does not work on homebridge (with gsh)

### ISSUE THREAD

**Issue by wish13yt** [wiiu-smarthome/homebridge-wiiu#1]
**Describe The Bug:**

Wii U does not turn off.
**To Reproduce:**

1. Use Google Home
2. Use Homebridge
3. Use homebridge-gsh
4. Have that all set up
5. Open the Google Home app
6. Click on Wii U
7. It will fail powering it off.
**Expected behavior:**

The Wii U turns off.
**Logs:**

```
[9/14/2024, 8:46:14 AM] [Google Smart Home] Received EXECUTE intent
[9/14/2024, 8:46:17 AM] [Wii U] Failed to shutdown Wii U
```
**Plugin Config:**

```json
{
    "bridge": {
        "name": "removed",
        "username": "removed",
        "port": 51651,
        "pin": "removed",
        "advertiser": "bonjour-hap"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "name": "Google Smart Home",
            "token": "removed",
            "notice": "Keep your token a secret!",
            "platform": "google-smarthome"
        },
        {
            "ip": "removed",
            "name": "Wii U",
            "platform": "HomebridgeWiiUPlugin"
        }
    ],
    "disabledPlugins": []
}

```

**Screenshots:**

**Environment:**

* **Plugin Version**: 1.0
* **Homebridge Version**: v1.8.4
* **Node.js Version**: v20.17.0
* **NPM Version**: 8.5.1
* **Operating System**:  Windows with WSL Ubuntu

**Comment by JPeisach** [comment]
Does everything else work? Normally that happens bc the server/console is offline.

**Comment by wish13yt** [comment]
> Does everything else work? Normally that happens bc the server/console is offline.

There is no everything else. :/

**Comment by JPeisach** [comment]
Try running `curl -X GET http://(Wii U ip address):(8572)/device/serial_id` and see if it returns anything.

**Comment by wish13yt** [comment]
Can't do it today, I'll try it tomorrow

**Comment by JPeisach** [comment]
This is entirely my fault. Fixed with https://github.com/ItzSwirlz/homebridge-wiiu/commit/e6d936d3e077c78df43d266763dd1475d77dde62 and homebridge-wiiu 1.0.1.
